#!/usr/bin/python
#coding: utf-8

import os 
import time
import signal
import readline

from pwinput import pwinput
from hashlib import sha256
from datetime import datetime


home = "/data/data/com.termux/files/home"

def banner():
  size = os.get_terminal_size().columns
  print("                            .?P#&&&&#P~                             ".center(size))
  print("                           G@@@@@@@@@@@&~                           ".center(size))
  print("          ^               P@&@@@@@@@@@@@@^               :          ".center(size))
  print("          P&:            .@#@@@@@@@@@@@@@&              J@.         ".center(size))
  print("           #@5           .&##   G@@~  ~@##            ~&@!          ".center(size))
  print("            G@@?          J&@~.J&!P&?:J@&~          ^B@#^           ".center(size))
  print("             !@@@J.       :&&B@@&~.@@@&&#:        ~B@&5.            ".center(size))
  print("               Y@@@P^       G~?@@@@@@YPY       .?&@@P^              ".center(size))
  print("                .Y&@@#?.    5@:YGGPJJ^@:    .~G@@@P^                ".center(size))
  print("                   !B@@&G?: .G#&#&&&&#J  .!P#@@&Y.                  ".center(size))
  print("                     .J#&&&#5!!PP55PY^^YB&&@&P^                     ".center(size))
  print("                        .?G&&@&#P?~YB&&@&#Y^                        ".center(size))
  print("                  !@@&Y   .~P&#&@@@&&&&B!.   7&@@Y                  ".center(size))
  print("              .. .^G?5@#?P#&&&&#GJYG#&&&&#GYG@G7G~. ..              ".center(size))
  print("             ?@@5&&@&@B@&?PY?~.      .^7YPJG@B&@@&&Y@@P             ".center(size))
  print("             :BB!.^^~^.G@~^.             ^:&&.^^^^.~B#~             ".center(size))
  print("                       .B&@5            !@&#:                       ".center(size))

array = []
class auto(object):
	def __init__(self, options):
		self.options = sorted(options)
		
	def complete(self, text, state):
		if state == 0:
			if text:
				self.matches = [s for s in self.options if s and s.startswith(text)]
			else :
				self.matches = self.options[:]
		try:
			return self.matches[state]
		except IndexError:
			return None
def complete(array):
	completer = auto(array)
	readline.set_completer(completer.complete)
	readline.parse_and_bind("tab:complete")

def getPID():
  os.system(f"ps | grep zsh > {home}/.pirate/PID")
  fp = open(f"{home}/.pirate/PID", "r").readlines()[0]
  PID = fp.strip().split(" ")[0]
  return PID
    
def checkAgent():
  if os.path.exists(f"{home}/.pirate/.user"):
    return True
  else:
    return False
    
def checkSession():
  if os.path.exists(f"{home}/.pirate/pirate_session-{sha256(str(datetime.now().strftime("%H")).encode()).hexdigest()}"):
    return True
  else:
    return False
    
def getDataAgent():
  if os.path.exists(f"{home}/.pirate/.user"):
    return open(f"{home}/.pirate/.user", "r").read()
  else:
    return "None"
    
def handler(signum, frame):
  PID = getPID()
  print()
  print("[!] Access Denied")
  os.system(f"kill -9 {PID}")
    
def main():
  PID = getPID()
  attempt = 3
  terminalSize = os.get_terminal_size().columns
  if checkAgent():
    if checkSession():
      os.system("clear")
      banner()
      print()
      print()
      print(f"{' '*int(os.get_terminal_size().lines)}]")
      print("\033[1A    [ Pirate v1.0-build ")
    else:
      while True:
        try:
          if attempt == 0:
            os.system(f"kill -9 {PID}")
          signal.signal(signal.SIGTSTP, handler)
          os.system("clear")
          banner()
          print()
          print()
          print("Pirate".center(terminalSize))
          print("--------------".center(terminalSize))
          print("Welcome back, Agent. Please log in to continue.".center(terminalSize))
          print()
          username = str(input("[?] Username: "))
          password = pwinput(prompt="[?] Password: ", mask="*")
          attempt -= 1
          if getDataAgent() == sha256(str(f"{username}:{password}").encode()).hexdigest():
            open(f"{home}/.pirate/pirate_session-{sha256(str(datetime.now().strftime('%d:%H')).encode()).hexdigest()}", "w").write(sha256(str(f"{username}:{password}").encode()).hexdigest())
            print()
            print("[*] Access Granted")
            time.sleep(2)
            os.system("clear")
            banner()
            print()
            print()
            print(f"{' '*int(os.get_terminal_size().lines)}]")
            print("\033[1A    [ Pirate v1.0-build ")
            break
          else:
            print(f"[!] Access Denied, Wrong Password, remaining {attempt} attempts")
            time.sleep(2)
            os.system("clear")
        except KeyboardInterrupt:
          print()
          print("[!] Access Denied")
          os.system(f"kill -9 {PID}")
        except EOFError:
          print()
          print("[!] Access Denied")
          os.system(f"kill -9 {PID}")
  else:
    os.system("clear")
    banner()
    print("Pirate".center(terminalSize))
    print("--------------".center(terminalSize))
    print("Welcome, agent. Please register to continue.".center(terminalSize))
    print()
    newUsername = str(input("[?] New Username: "))
    newPassword = pwinput(prompt="[?] New Password: ", mask="*")
    with open(f"{home}/.pirate/.user", "w") as fu:
      fu.write(sha256(str(f"{newUsername}:{newPassword}").encode()).hexdigest())
      fu.close()
      open(f"{home}/.pirate/pirate_session-{sha256(str(datetime.now().strftime('%d:%H')).encode()).hexdigest()}", "w").write(sha256(str(f"{newUsername}:{newPassword}").encode()).hexdigest())
      print()
      print("[*] Successful registration.")
      time.sleep(2)
      os.system("clear")
      print(f"{' '*int(os.get_terminal_size().lines)}]")
      print("\033[1A    [ Pirate v1.0-build ")
      
if __name__ == "__main__":
  main()
